### ISSUE TITLE
Avoid adding `end` directly after writing `do` in templates

### ISSUE THREAD

**Issue by nicolasblanco** [xolan/slime.vscode#1]
Hello,

do you know if there's a way to avoid Visual Code to directly add `end` in templates just after writing `do` because in Slime templates the `end` keyword is generally not required...

![ScreenFlow](https://user-images.githubusercontent.com/12682/64478228-12b6df00-d1ae-11e9-868a-8dcbcb7cf433.gif)

**Comment by xolan** [comment]
Hi,

"brackets" are defined here https://github.com/xolan/slime.vscode/blob/master/language-configuration.json , so you can probably just remove do/end from those entries.

**Comment by nicolasblanco** [comment]
Hey @xolan,

I had no idea about how vscode extensions were working, so thanks a lot for the quick hint!
👍 

I've just removed `do` and `->` of the `autoClosingPairs` config to try. Now the behaviour feels much better for me because in Slime those keywords are more often closed by indentation.

**Comment by xolan** [comment]
Glad to hear it!

**Comment by lobo-tuerto** [comment]
How do you access that configuration from within VSCode to modify the `autoClosingPairs`?

I'm having the same problem... D:

**Comment by xolan** [comment]
Hi @lobo-tuerto 

According to VSCode[1] docs, the extensions are installed here by default:

* Windows: `%USERPROFILE%\.vscode\extensions`
* macOS: `~/.vscode/extensions`
* Linux: `~/.vscode/extensions`

Once located, navigate to `extensions/xolan.slime-1.0.0/language-configuration.json`, where you will find the file mentioned above.

I might add this as a configuration option at a later date.

[1] https://code.visualstudio.com/docs/editor/extension-gallery#_where-are-extensions-installed

**Comment by lobo-tuerto** [comment]
@xolan hello!

Do you have any news on making those settings configurable on `settings.json`?
It'll be really nice to have a single settings file to configure the extension instead of going inside the config file on every new install. :|

**Comment by xolan** [comment]
> @xolan hello!
> 
> Do you have any news on making those settings configurable on `settings.json`?
> It'll be really nice to have a single settings file to configure the extension instead of going inside the config file on every new install. :|

Hi! I don't really use slime anymore myself, but ill see what I can do after the weekend.

**Comment by xolan** [comment]
I've now published version 1.0.2 which has these autoclosing pairs disabled.

As for making it configurable, I'm tracking this discussion: https://github.com/microsoft/vscode/issues/38352
